package longfrog;

import java.util.ArrayList;
import java.util.List;

import longfrog.command.Command;
import longfrog.exception.LongfrogException;
import longfrog.parser.Parser;
import longfrog.storage.Storage;
import longfrog.task.TaskList;
import longfrog.ui.Ui;

/** Coordinates command parsing, task persistence, and the console UI. */
public class Longfrog {
    private static final String FILE_PATH = "data/longfrog.txt";
    private final Storage storage;
    private final TaskList taskList;
    private final Ui ui;
    private final List<String> responseMessages;
    private final Ui responseUi;
    private final Parser parser;
    private boolean exitRequested;

    /** Creates Longfrog using the supplied task storage file. */
    public Longfrog(String filePath) {
        ui = new Ui();
        responseMessages = new ArrayList<>();
        responseUi = new Ui(responseMessages::add);
        storage = new Storage(filePath);
        TaskList loadedTasks;
        try {
            loadedTasks = new TaskList(storage.load());
        } catch (LongfrogException e) {
            ui.showLoadingError();
            loadedTasks = new TaskList();
        }
        taskList = loadedTasks;
        parser = new Parser(taskList);
    }

    /** Starts the command loop and continues until the user enters {@code bye}. */
    public void run() {
        ui.showGreeting();

        boolean isExit = false;
        while (!isExit) {
            String userInput = ui.readCommand();

            ui.showLine();
            isExit = executeCommand(userInput, ui);

            ui.showEmptyLine();
            ui.showLine();
            ui.showEmptyLine();
        }

        ui.close();
    }

    /**
     * Processes a GUI message and returns Longfrog's response as displayable text.
     *
     * @param input the raw command entered by the user
     * @return the response generated by Longfrog
     */
    public String getResponse(String input) {
        responseMessages.clear();
        exitRequested = executeCommand(input, responseUi);
        return String.join(System.lineSeparator(), responseMessages);
    }

    /**
     * Returns whether the most recent GUI command requested application exit.
     *
     * @return whether the most recent command was {@code bye}
     */
    public boolean isExitRequested() {
        return exitRequested;
    }

    /**
     * Executes a parsed command and persists any resulting task-list changes.
     *
     * @param input the raw command to execute
     * @param outputUi the UI that receives the command response
     * @return whether the command requested application exit
     */
    private boolean executeCommand(String input, Ui outputUi) {
        try {
            Command command = parser.parse(input);
            boolean isExit = command.execute(outputUi);
            if (!storage.save(taskList.getAll())) {
                outputUi.showSavingError();
            }
            return isExit;
        } catch (LongfrogException e) {
            outputUi.showMessage(e.getMessage());
            return false;
        }
    }

    /**
     * Starts Longfrog using its default save-file location.
     *
     * @param args command-line arguments, which are ignored
     */
    public static void main(String[] args) {
        new Longfrog(FILE_PATH).run();
    }
}
